services:
  - type: web
    name: cleanz24-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FAST2SMS_API_KEY
        sync: false
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        value: "1232168166656706"
      - key: WHATSAPP_TEMPLATE_NAME
        value: cleanz24_app
